### ISSUE TITLE
Зачем  info.s?

### ISSUE THREAD

**Issue by kloun** [xverizex/translate#1]
зачем усложнять, если можно сделать .h-файл?
Никогда ещё не видел такого...

pull request примешь?

**Comment by xverizex** [comment]
Мне так захотелось. Если я напишу на си в .h, произойдёт то что я написал в info.s.

**Comment by kloun** [comment]
быстрее будет собираться хотя бы, без вызова gas.
и да, может я и ошибаюсь, но это вроде бы непортируемо на другие архитектуры.

**Comment by xverizex** [comment]
Различия в архитектурах в названиях регистров и размером в регистрах и размера кадров в стеке. У меня есть ipcalc где файлы convert.s для i386, convert64.s для x86_64. Можешь увидеть различия, но выполняют одну и ту же задачу. Что же насчёт info.s, так он подойдёт к любым архитектурам.

**Comment by kloun** [comment]
А для powerpc, например? в си бы было кроссплатформенно и легче поддерживаемо. ассемблер вообще к ПРИКЛАДНЫМ задачам - неоптимальный выбор, кроме тех, для которых важно быстродействие. ipcalc к таким вряд ли относится.

**Comment by kloun** [comment]
и да, прими, если согласен с исправлениями, мой PR #2 .

**Comment by kloun** [comment]
я не вправе указывать тебе, но ты меня пойми: я просто ещё ни разу не видел такого. вставки на асме, если и были, только критичные к производительности участки кода затрагивали...

**Comment by xverizex** [comment]
Ну почему, в любой программе лучше было бы, если бы она быстрее выполнилась из-за ассемблера. В ассемблере есть то, что может заменить даже некоторые функции на си, а это уже быстрее значит будет. А если я это знаю, значит я знаю где можно быстрее сделать выполняемый код не обращаясь лишний раз к функциям операционной системы.

**Comment by kloun** [comment]
а info.s - никаким боком тут не валялся, ведь это всего лишь header.

**Comment by xverizex** [comment]
header? Нет. Когда ты компилируешь с header, header нужно указать в #include. info.s нужен, и он идёт вместе с программой. Там содержится важная строка, для которой я захотел специально на ассемблере написать. Вот и всё.

**Comment by kloun** [comment]
важная? да она не влияет на функциональность программы... ну делай как
хочешь.
и да, ответь в ветке про пуллреквест.

3 октября 2016 г., 19:44 пользователь Dmitry <notifications@github.com>
написал:

**Comment by xverizex** [comment]
Я там пуллреквест отменил.
