### ISSUE TITLE
неиспользуемый параметр "typeflag"

### ISSUE THREAD

**Issue by kloun** [xverizex/translate#5]
main.c: В функции «found»:
main.c:355:7: предупреждение: unused parameter «typeflag» [-Wunused-parameter]
   int typeflag, struct FTW *ftwbuf){
       ^~~~~~~~

**Comment by xverizex** [comment]
Ну видишь, я его не использую.

**Comment by kloun** [comment]
так удали его, блин... или ты планируешь его впоследствии использовать?

2016-10-04 18:39 GMT+03:00 Dmitry <notifications@github.com>:
